[Interface]
PrivateKey = 2JjOHi0MnNfU2WExf3I+0KkqDTBW4kRjdbI/tqb1AWo=
Address = 10.13.13.4/24
DNS = 1.1.1.1

[Peer]
PublicKey = AnInOUeaF9cXhCZEJf3LEBcjeQB/HriMC3TangOjEC4=
AllowedIPs = 0.0.0.0/0
Endpoint = us.597818601.xyz:29188
PersistentKeepalive = 25
