[Interface]
PrivateKey = GFMjJEA+1lyqGFoV2SAdZgxTPLZENSQAajccBRfa414=
Address = 10.18.18.3/32
DNS = 1.1.1.1, 8.8.8.8
MTU = 1380

[Peer]
PublicKey = LHDPJVs5Mrnwvlaj85qBnEY88P+rrIdkX2VxSr5kcgk=
AllowedIPs = 0.0.0.0/0
Endpoint = us.597818601.xyz:51820
PersistentKeepalive = 25
